
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[538] =
    {   0,
        0,    0,   90,   89,   86,   87,   48,   72,   58,   75,
       66,   67,   62,   59,   69,   60,   68,   61,   77,   71,
       70,   52,   89,   50,   82,   82,   82,   82,   30,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   64,
       76,   65,   63,   73,   74,   88,   86,   48,   72,   58,
       75,   66,   67,   62,   59,   69,   60,   68,   61,   77,
       71,   70,   52,   88,   50,   82,   82,   82,   82,   30,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       64,   76,   65,   63,   73,   74,    0,   83,    0,   56,
       57,    0,   85,    0,   77,   49,   53,   55,   54,   51,

       82,   82,   82,   82,   82,   31,   82,   82,   82,   82,
       82,   82,   82,   82,   82,    0,   82,   82,    0,   82,
        0,   18,   82,   82,   82,    5,   82,   82,   79,    0,
        0,    0,   85,   78,   82,   32,    0,   82,   82,   82,
       82,   82,   82,   82,   82,    0,   29,   82,   82,   82,
        0,   82,   82,   82,    0,    0,   82,   82,   82,    0,
        0,    0,    0,   36,   82,    0,    0,   82,   82,   82,
       82,   82,   82,   82,   82,    2,   82,    0,    0,   84,
       82,   32,   82,   45,   82,   82,   82,    0,   82,   82,
        8,   82,    0,    0,    0,   82,   82,   82,   82,   82,

       82,    0,   82,   82,    0,    0,   39,   82,   82,    0,
        0,   82,   82,   82,    0,    0,    0,    0,   36,   36,
       36,   82,   20,   82,   82,   82,   35,   82,   82,   82,
        0,   82,   82,   82,   82,   82,   82,   19,    0,    0,
       82,   82,   81,    8,    8,    0,    0,    0,    0,    0,
       82,   82,   82,   82,   82,   82,    6,   82,   82,    0,
        0,    0,   82,   82,    0,    0,   82,   82,    0,    0,
       82,   82,   82,    0,    0,    0,    0,   82,   37,   82,
       33,   82,   82,   12,    0,    0,   82,    0,   82,   82,
       82,   82,   82,   19,   19,   82,   82,    0,    0,    0,

        0,    0,    0,    6,    0,   82,   82,    6,   82,   82,
       82,   82,   82,    1,   23,    0,    0,    0,    0,    0,
        0,   28,   82,    0,    0,   82,   17,    0,    0,   15,
       42,   40,    0,    0,    0,    0,    0,   82,   82,   43,
       82,   12,   12,   82,    0,    0,   82,   82,   82,   41,
       82,   44,   38,    0,    0,    0,    0,    0,    0,    0,
        0,    1,   82,   82,    9,   82,   21,   82,   82,   82,
       23,   23,   23,    0,   23,    0,   27,   28,   28,   82,
       11,   16,   17,   17,   42,   40,   42,   40,    0,   82,
       82,   34,   82,    0,    0,   82,   82,   82,   13,   38,

        0,    0,    9,    0,    0,    0,    0,   21,    0,    0,
        0,    0,   82,   82,   82,   82,    7,   82,    0,   23,
       23,   22,   10,   16,   16,    0,   82,   82,   82,   82,
        0,    0,   82,    4,    3,    0,    0,    9,    9,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,   82,
       82,   25,   82,   82,    0,    0,    0,   46,   82,   82,
        2,    0,    0,   82,    0,    0,   25,    0,    0,    0,
        0,    0,    0,    0,    7,    7,    0,    0,    0,   82,
       47,   82,   82,    0,    0,   46,   82,   82,    2,    2,
       80,    0,   47,   25,   25,   25,    0,   25,    0,    0,

        0,    0,    0,   14,   82,   82,    0,    0,   24,   82,
       14,   25,   25,    0,    0,    0,    0,   82,    1,    0,
        0,   24,    0,    1,    0,    0,   82,    1,    1,    0,
        1,    1,   82,    0,   26,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   24,   24,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   24,   43,   24,   44,
       45,   46,   47,   48,   49,    1,   50,   24,   51,   52,

       53,   54,   55,   56,   57,   24,   24,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   24,   69,
       24,   70,   71,    1,   72,    1,    1,    1,   73,    1,
       74,    1,    1,    1,   75,    1,   76,    1,    1,    1,
       77,    1,    1,    1,    1,    1,   78,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       79,    1,   80,    1,    1,    1,   81,    1,   82,    1,
        1,    1,   83,    1,    1,    1,    1,    1,   84,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   85,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[86] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[544] =
    {   0,
        0,   85,  888, 1103, 1103, 1103,  837, 1103, 1103,    0,
     1103, 1103, 1103,  821, 1103,  814, 1103,  160,  157,  656,
     1103,  159,  597,  503,  143,    0,  155,  150,  150,  156,
      151,  159,  168,  169,  147,  179,  168,  169,  177, 1103,
     1103, 1103, 1103, 1103, 1103, 1103, 1103,  432, 1103, 1103,
        0, 1103, 1103, 1103,  418, 1103,  399, 1103,  182,  209,
      387, 1103,  214,  345,  343,  199,    0,  210,  205,  206,
      211,  204,  220,  225,  226,  200,  236,  219,  235,  256,
     1103, 1103, 1103, 1103, 1103, 1103,  354, 1103,  348, 1103,
     1103,  281,    0,  338,  272, 1103, 1103, 1103, 1103, 1103,

        0,  240,  243,  252,  259,    0,  257,  273,  276,  266,
      269,  273,  276,  272,  285,  237,  301,  288,  270,  296,
      252,  296,  307,  307,  329,  316,  313,  316, 1103,  370,
      379,  381,    0,  318,  325,    0,  311,  352,  343,  348,
      348,  371,  361,  377,  359,  326,  392,  378,  384,  383,
      328,  389,  389,  386,  389,  394,  388,  401,  402,  395,
      406,  398,  413,    0,  415,  415,  416,  415,  432,  422,
      437,  437,  434,  435,  448,  444,  452,  481,  486, 1103,
      442, 1103,  456,    0,  445,  449,  451,  428,  461,  473,
        0,  468,  482,  487,  486,  481,  493,  500,  491,  507,

      508,  436,  490,  496,  510,  511,    0,  504,  520,  518,
      521,  524,  523,  526,  532,  534,  535,  538,    0, 1103,
     1103,  535,    0,  537,  546,  535,    0,  536,  539,  544,
      506,  544,  560,  556,  548,  561,  556,    0,  562,  566,
      574,  564,    0, 1103, 1103,  573,  585,  586,  588,  594,
      582,  595,  596,  591,  590,  596,  600,  599,  604,  569,
      617,  619,  618,  617,  625,  627,  636,  626,  637,  639,
      622,  633,  635,  638,  639,  640,  641,  664,    0,  649,
        0,  653,  646,    0,  648,  650,  649,  634,  667,  655,
      678,  676,  670, 1103, 1103,  689,  691,  679,  693,  695,

      688,  685,  689,  691,  688,  686,  693,    0,  706,  707,
      707,  708,  712,  706,    0,  703,  705,  708,  244,  710,
      222,    0,  712,  720,  725,  736,  722,  730,  735,    0,
        0,    0,  737,  739,  740,  741,  752,  755,  751,    0,
      756, 1103, 1103,  757,  743,  746,  762,  757,  754,    0,
      760,    0,  765,  758,  769,  756,  732,  787,  794,  794,
      797,  791,  801,  794,    0,  804,    0,  802,  796,  809,
     1103, 1103, 1103,  799, 1103,  800,  797, 1103, 1103,  798,
        0,    0,  800,  801, 1103, 1103, 1103, 1103,  818,  804,
      831,    0,  818,  823,  826,  836,  835,  844,    0,    0,

      823,  842, 1103,  833,  854,  855,  805, 1103,  854,  850,
      815,  864,  857,  862,  863,  873,    0,  859,  829, 1103,
     1103,    0,    0, 1103, 1103,  864,  871,  875,  883,  873,
      882,  884,  878,    0,    0,  885,  890, 1103, 1103,  886,
      848,  900,  903,  904, 1103,  896,  898,  892,  864,  904,
      925,    0,  920,  925,  912,  913,  923,    0,  921,  929,
        0,  925,  926,  931,  927,  945, 1103,  936,  937,  938,
      206,  939,  170,  945, 1103, 1103,  952,  940,  941,  951,
        0,  961,  965,  974,  976, 1103,  969,  966, 1103, 1103,
        0,  972, 1103, 1103, 1103, 1103,  975, 1103,  976,  980,

      983,  988,  989,    0,  990,  979,  988,  990,    0,  988,
     1103, 1103, 1103,  997,  986,  995,  997,  997,    0,  995,
      996,    0, 1004, 1103, 1007, 1009, 1013, 1103, 1103, 1015,
     1103, 1103, 1021, 1023,    0, 1103, 1103, 1084,  203, 1086,
     1090, 1094, 1098
    } ;

static const flex_int16_t yy_def[544] =
    {   0,
      537,  537,  537,  537,  537,  537,  538,  537,  537,  539,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  537,
      537,  537,  537,  537,  537,  537,  537,  538,  537,  537,
      539,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      537,  537,  537,  537,  537,  537,  538,  537,  537,  537,
      537,  541,  542,  537,  537,  537,  537,  537,  537,  537,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  537,  540,  540,  537,  540,
      537,  540,  540,  540,  540,  540,  540,  540,  537,  541,
      541,  543,  542,  537,  540,  540,  537,  540,  540,  540,
      540,  540,  540,  540,  540,  537,  540,  540,  540,  540,
      537,  540,  540,  540,  537,  537,  540,  540,  540,  537,
      537,  537,  537,  540,  540,  537,  537,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  541,  541,  537,
      540,  537,  540,  540,  540,  540,  540,  537,  540,  540,
      540,  540,  537,  537,  537,  540,  540,  540,  540,  540,

      540,  537,  540,  540,  537,  537,  540,  540,  540,  537,
      537,  540,  540,  540,  537,  537,  537,  537,  540,  537,
      537,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      537,  540,  540,  540,  540,  540,  540,  540,  537,  537,
      540,  540,  540,  537,  537,  537,  537,  537,  537,  537,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  537,
      537,  537,  540,  540,  537,  537,  540,  540,  537,  537,
      540,  540,  540,  537,  537,  537,  537,  540,  540,  540,
      540,  540,  540,  540,  537,  537,  540,  537,  540,  540,
      540,  540,  540,  537,  537,  540,  540,  537,  537,  537,

      537,  537,  537,  537,  537,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  537,  537,  537,  537,  537,
      537,  540,  540,  537,  537,  540,  540,  537,  537,  540,
      540,  540,  537,  537,  537,  537,  537,  540,  540,  540,
      540,  537,  537,  540,  537,  537,  540,  540,  540,  540,
      540,  540,  540,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  540,  540,  540,  540,  540,  540,  540,  540,
      537,  537,  537,  537,  537,  537,  540,  537,  537,  540,
      540,  540,  537,  537,  537,  537,  537,  537,  537,  540,
      540,  540,  540,  537,  537,  540,  540,  540,  540,  540,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  540,  540,  540,  540,  540,  540,  537,  537,
      537,  540,  540,  537,  537,  537,  540,  540,  540,  540,
      537,  537,  540,  540,  540,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  540,
      540,  540,  540,  540,  537,  537,  537,  540,  540,  540,
      540,  537,  537,  540,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  540,
      540,  540,  540,  537,  537,  537,  540,  540,  537,  537,
      540,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  540,  540,  540,  537,  537,  540,  540,
      537,  537,  537,  537,  537,  537,  537,  540,  540,  537,
      537,  540,  537,  537,  537,  537,  540,  537,  537,  537,
      537,  537,  540,  537,  540,  537,    0,  537,  537,  537,
      537,  537,  537
    } ;

static const flex_int16_t yy_nxt[1189] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   26,   26,
       31,   32,   33,   34,   35,   36,   26,   37,   38,   26,
       26,   39,   26,   26,   40,   41,   42,   43,    4,   25,
       27,   28,   29,   30,   26,   26,   31,   32,   33,   34,
       35,   36,   26,   37,   38,   26,   26,   39,   26,   26,
       44,   45,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,   46,   47,    6,   46,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   67,   67,   72,   73,   74,   75,   76,
       77,   67,   78,   79,   67,   67,   80,   67,   67,   81,
       82,   83,   84,   46,   66,   68,   69,   70,   71,   67,
       67,   72,   73,   74,   75,   76,   77,   67,   78,   79,
       67,   67,   80,   67,   67,   85,   86,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       92,   94,   96,   95,  102,   93,  106,  104,  109,   97,
       98,  105,  103,  107,  112,  113,  110,  122,  108,  114,
      117,  120,   92,  115,  125,  126,  111,   93,  118,  127,

      102,  123,  106,  128,  104,  109,   89,  105,  103,  107,
      112,  113,  110,  122,  108,  114,  124,  117,  120,  115,
      125,  126,  111,   94,  118,   95,  127,   96,  123,  128,
      102,  106,  104,  109,   97,   98,  105,  112,  103,  107,
      122,  110,  124,  116,  108,  125,  113,  117,  120,  499,
      114,  111,  119,  121,  115,  118,  102,  106,  123,  104,
      109,  126,  105,  112,  103,  107,  122,  110,  135,  136,
      108,  125,  113,  124,  117,  120,  114,  111,  127,  497,
      115,  118,  128,  131,  131,  123,   94,  126,   95,  138,
      139,  132,  140,  141,  135,  136,  142,  143,  147,  124,

      144,  376,  148,  149,  116,  127,  152,  145,  128,  119,
      121,  153,  150,  154,  155,  138,  139,  374,  140,  141,
      156,  159,  142,  143,  147,  166,  144,  137,  148,  149,
      164,  167,  152,  145,  134,  168,  165,  153,  150,  154,
      157,  171,  160,  158,  169,  170,  161,  159,  162,  175,
      176,  172,  163,  177,  134,  129,  164,  151,   88,  181,
      146,  168,  165,  100,  173,   99,  157,  171,  174,  158,
      169,  170,  131,  131,  183,  175,  176,  184,  172,  177,
      132,  131,  131,  179,  179,  181,  182,  185,  186,  132,
      173,  132,  182,  187,  174,  189,  180,  192,  190,  191,

      193,  183,  201,  184,  205,  195,  194,   96,  203,  204,
      206,  207,   91,  185,  186,  208,  209,  210,  196,  197,
      187,  189,  211,  192,  190,  212,  191,  198,  201,   90,
      199,  213,  214,  200,  203,  204,   88,  215,  207,  216,
      217,  208,  209,  210,  196,  197,  218,  219,  211,  220,
      221,  212,  222,  198,  223,  188,  199,  213,  214,  200,
      224,  225,  202,  215,  228,  216,  217,  226,  227,  229,
      230,  237,  218,  219,  232,  220,  221,  233,  222,  234,
      235,  223,  236,  131,  131,  238,  224,  225,  131,  131,
      228,  132,  241,  226,  227,  229,  132,  230,  237,  242,

      232,  239,  243,  233,  244,  234,  235,  240,  236,  245,
      261,  238,  246,  247,  251,  253,  262,  257,  241,  252,
      263,  248,  255,  100,  249,  242,  264,  250,  243,  258,
      259,  244,  231,  254,  265,  266,  245,  256,  246,  247,
      251,  267,  253,  257,  268,  252,  263,  248,  269,  255,
      249,  270,  264,  250,  271,  272,  258,  259,  273,  254,
      265,  266,  274,  256,  275,  276,  287,  267,  277,  278,
      268,  279,  280,  281,  269,  282,  283,  270,  284,  285,
      271,  272,  289,  292,  273,  286,  290,  291,  274,  293,
      275,  276,  260,  287,  277,  278,  294,  279,  280,  281,

      295,  282,  283,  296,  284,  297,  298,  300,  302,  289,
      292,  299,  290,  291,  304,  293,  305,   99,  306,  307,
      309,  308,  294,  303,  310,  301,  295,  311,  288,  296,
      312,  297,  298,  313,  300,  302,  314,  299,  315,  318,
      304,  320,  316,  305,  306,  307,  309,  308,  317,  303,
      310,  301,  322,  311,  323,  324,  312,  325,  326,  313,
      327,  328,  314,  329,  315,  330,  318,  331,  320,  332,
      333,  334,  335,  336,  339,  340,   96,  337,  322,  341,
      323,  324,  342,  325,  343,  326,  327,  328,  338,  329,
      344,  330,  347,  331,  348,  332,  333,  334,  335,  336,

      339,  319,  340,  321,  349,  341,  345,  350,  342,  351,
      343,  352,  346,  353,  338,  354,  344,  355,  347,  356,
      348,  358,  359,  360,  361,  362,  363,  364,  365,  367,
      349,  366,  368,  350,  369,  351,  370,  371,  352,  372,
      353,  354,  373,  355,  375,  356,  377,  358,  359,  360,
      361,  362,  363,  364,  378,  365,  367,  366,  368,  379,
      382,  369,  370,  371,  383,  372,  380,  381,  373,  384,
      375,  385,  377,  386,  387,  388,  389,  390,  403,  357,
      378,  391,  392,  393,  394,  379,  382,  395,  396,  397,
      383,  398,  380,  381,  399,  384,  400,  385,  401,  386,

      387,  388,  389,  402,  390,  403,  404,  391,  392,  393,
      394,  406,  405,  395,  396,  397,  408,  398,  409,  410,
      399,  412,  400,  413,  401,  414,  415,   91,  416,  402,
      417,  418,   90,  420,  421,  422,  423,  406,  424,  425,
      426,   88,  427,  408,  409,  436,  410,  412,  430,  431,
      413,  414,  432,  415,  416,  438,  417,  428,  418,  420,
      421,  422,  423,  429,  424,  425,  433,  426,  427,  434,
      435,  407,  436,  437,  430,  431,  439,  440,  432,  442,
      444,  411,  438,  428,  445,  443,  448,  537,  446,  429,
      450,  451,  433,  419,  447,  434,  435,  452,  453,  437,

      454,  455,  457,  439,  440,  458,  444,  456,  459,  460,
      445,  461,  462,  448,  463,  464,  450,  451,  465,  466,
      467,  468,  470,  452,  453,  472,  454,  469,  457,  474,
      475,  458,  476,  477,  459,  460,  478,  461,  462,  441,
      463,  464,  479,  480,  465,  466,  467,  481,  449,  470,
      482,  483,  472,  484,  485,  474,  475,  486,  476,  477,
      487,  537,  488,  489,  490,  491,  492,  493,  537,  480,
      494,  495,  496,  498,  481,  500,  482,  483,  501,  484,
      485,  502,  503,  486,  471,  504,  487,  473,  488,  489,
      490,  491,  492,  505,  493,  506,  494,  495,  496,  498,

      507,  500,  508,  509,  501,  510,  511,  502,  503,  512,
      513,  504,  514,  515,  516,  517,  518,  519,  520,  505,
      521,  506,  522,  523,  524,  525,  507,  526,  508,  509,
      527,  510,  511,  528,  529,  512,  513,  530,  514,  515,
      516,  517,  518,  519,  520,  531,  521,  532,  522,  523,
      524,  525,  533,  526,  534,  535,  527,  536,  537,  528,
      529,  537,  537,  530,  537,  537,  537,  537,  537,  537,
      537,  531,  537,  532,  537,  537,  537,  537,  533,  537,
      534,  535,  537,  536,   87,   87,   87,   87,  101,  101,
      130,  130,  130,  130,  133,  537,  133,  133,  178,  178,

      178,  178,    3,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537
    } ;

static const flex_int16_t yy_chk[1189] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
       18,   19,   22,   19,   25,   18,   28,   27,   30,   22,
       22,   27,   25,   29,   31,   32,   30,   35,   29,   32,
       33,   34,   59,   32,   37,   38,   30,   59,   33,   39,

       25,   36,   28,   39,   27,   30,  539,   27,   25,   29,
       31,   32,   30,   35,   29,   32,   36,   33,   34,   32,
       37,   38,   30,   60,   33,   60,   39,   63,   36,   39,
       66,   69,   68,   71,   63,   63,   68,   72,   66,   70,
       76,   71,   36,   32,   70,   78,   73,   74,   75,  473,
       73,   71,   33,   34,   73,   74,   66,   69,   77,   68,
       71,   79,   68,   72,   66,   70,   76,   71,  102,  103,
       70,   78,   73,   77,   74,   75,   73,   71,   80,  471,
       73,   74,   80,   92,   92,   77,   95,   79,   95,  104,
      104,   92,  105,  107,  102,  103,  107,  108,  110,   77,

      109,  321,  111,  112,   73,   80,  113,  109,   80,   74,
       75,  114,  112,  115,  116,  104,  104,  319,  105,  107,
      116,  118,  107,  108,  110,  121,  109,  103,  111,  112,
      120,  121,  113,  109,  134,  122,  120,  114,  112,  115,
      117,  124,  119,  117,  123,  123,  119,  118,  119,  126,
      127,  125,  119,  128,   94,   89,  120,  112,   87,  135,
      109,  122,  120,   65,  125,   64,  117,  124,  125,  117,
      123,  123,  130,  130,  138,  126,  127,  139,  125,  128,
      130,  131,  131,  132,  132,  135,  137,  140,  141,  131,
      125,  132,  137,  142,  125,  143,  132,  145,  143,  144,

      146,  138,  148,  139,  151,  147,  146,   61,  149,  150,
      151,  152,   57,  140,  141,  153,  154,  155,  147,  147,
      142,  143,  156,  145,  143,  157,  144,  147,  148,   55,
      147,  158,  159,  147,  149,  150,   48,  160,  152,  161,
      162,  153,  154,  155,  147,  147,  163,  165,  156,  166,
      167,  157,  168,  147,  169,  142,  147,  158,  159,  147,
      170,  171,  148,  160,  173,  161,  162,  172,  172,  174,
      175,  186,  163,  165,  176,  166,  167,  177,  168,  181,
      183,  169,  185,  178,  178,  187,  170,  171,  179,  179,
      173,  178,  189,  172,  172,  174,  179,  175,  186,  190,

      176,  188,  192,  177,  193,  181,  183,  188,  185,  194,
      202,  187,  195,  195,  196,  197,  202,  199,  189,  196,
      203,  195,  198,   24,  195,  190,  204,  195,  192,  200,
      201,  193,  175,  197,  205,  206,  194,  198,  195,  195,
      196,  208,  197,  199,  209,  196,  203,  195,  210,  198,
      195,  211,  204,  195,  212,  213,  200,  201,  214,  197,
      205,  206,  215,  198,  216,  217,  232,  208,  218,  222,
      209,  224,  225,  226,  210,  228,  229,  211,  230,  231,
      212,  213,  233,  236,  214,  231,  234,  235,  215,  237,
      216,  217,  201,  232,  218,  222,  239,  224,  225,  226,

      240,  228,  229,  241,  230,  242,  246,  247,  248,  233,
      236,  246,  234,  235,  249,  237,  250,   23,  251,  252,
      253,  252,  239,  248,  254,  247,  240,  255,  232,  241,
      256,  242,  246,  257,  247,  248,  258,  246,  259,  261,
      249,  262,  260,  250,  251,  252,  253,  252,  260,  248,
      254,  247,  263,  255,  264,  265,  256,  266,  267,  257,
      268,  269,  258,  270,  259,  271,  261,  272,  262,  273,
      274,  275,  276,  277,  280,  282,   20,  278,  263,  283,
      264,  265,  285,  266,  286,  267,  268,  269,  278,  270,
      287,  271,  289,  272,  290,  273,  274,  275,  276,  277,

      280,  261,  282,  262,  291,  283,  288,  292,  285,  293,
      286,  296,  288,  297,  278,  298,  287,  299,  289,  300,
      290,  301,  302,  303,  304,  305,  306,  307,  309,  311,
      291,  310,  312,  292,  313,  293,  314,  316,  296,  317,
      297,  298,  318,  299,  320,  300,  323,  301,  302,  303,
      304,  305,  306,  307,  324,  309,  311,  310,  312,  325,
      327,  313,  314,  316,  328,  317,  326,  326,  318,  329,
      320,  333,  323,  334,  335,  336,  337,  338,  356,  300,
      324,  339,  341,  344,  345,  325,  327,  346,  347,  348,
      328,  349,  326,  326,  351,  329,  353,  333,  354,  334,

      335,  336,  337,  355,  338,  356,  357,  339,  341,  344,
      345,  358,  357,  346,  347,  348,  359,  349,  360,  361,
      351,  362,  353,  363,  354,  364,  366,   16,  368,  355,
      369,  370,   14,  374,  376,  377,  380,  358,  383,  384,
      389,    7,  390,  359,  360,  401,  361,  362,  393,  394,
      363,  364,  395,  366,  368,  404,  369,  391,  370,  374,
      376,  377,  380,  391,  383,  384,  396,  389,  390,  397,
      398,  358,  401,  402,  393,  394,  405,  406,  395,  407,
      409,  361,  404,  391,  410,  407,  412,    3,  411,  391,
      413,  414,  396,  370,  411,  397,  398,  415,  416,  402,

      418,  419,  426,  405,  406,  427,  409,  419,  428,  429,
      410,  430,  431,  412,  432,  433,  413,  414,  436,  437,
      440,  441,  442,  415,  416,  443,  418,  441,  426,  444,
      446,  427,  447,  448,  428,  429,  449,  430,  431,  406,
      432,  433,  449,  450,  436,  437,  440,  451,  412,  442,
      453,  454,  443,  455,  456,  444,  446,  457,  447,  448,
      459,    0,  460,  462,  463,  464,  465,  466,    0,  450,
      468,  469,  470,  472,  451,  474,  453,  454,  477,  455,
      456,  478,  479,  457,  442,  480,  459,  443,  460,  462,
      463,  464,  465,  482,  466,  483,  468,  469,  470,  472,

      484,  474,  485,  487,  477,  488,  492,  478,  479,  497,
      499,  480,  500,  501,  502,  503,  505,  506,  507,  482,
      508,  483,  510,  514,  515,  516,  484,  517,  485,  487,
      518,  488,  492,  520,  521,  497,  499,  523,  500,  501,
      502,  503,  505,  506,  507,  525,  508,  526,  510,  514,
      515,  516,  527,  517,  530,  533,  518,  534,    0,  520,
      521,    0,    0,  523,    0,    0,    0,    0,    0,    0,
        0,  525,    0,  526,    0,    0,    0,    0,  527,    0,
      530,  533,    0,  534,  538,  538,  538,  538,  540,  540,
      541,  541,  541,  541,  542,    0,  542,  542,  543,  543,

      543,  543,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <string.h>
#define DEBUG

char ident[100];

int nlinhas = 1;
char vlr_int[100];

// funcao para contar linhas dentro de um comentario de bloco
void contaLinhas(char *str){
	char *aux = (char*)malloc(strlen(str)*sizeof(char));
	strcpy(aux, str);
	while (*aux != '\0'){
		if (*aux == '\n' ){
			nlinhas++;
		}
		//printf("%s ", aux);
		aux++;
	}
};
#line 904 "lex.yy.c"
/* definicoes */
#line 906 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "scanner.l"


#line 1129 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 538 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1103 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas);
																			#endif
																			return token_var_fim;
																		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_var;
																		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_char;
																		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_algoritmo;
																		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_if;
																		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "scanner.l"
{
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_then_end;
																		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_else_end;
																		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_do;
																		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_do_end;
																		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_strings;
																		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_string;
																		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_else;
																		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_while;
																		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "scanner.l"
{		
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_while_end;
																		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_matriz;
																		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 121 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_booleans;
																		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 127 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_boolean;
																		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 133 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_or;
																		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 139 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_then;
																		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 145 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_for;
																		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 151 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_for_end;
																		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 157 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_ints;
																		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 163 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_func;
																		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 169 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_proc;
																		}																		
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 175 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_func_fim;
																		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 181 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_proc_fim;
																		}					
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 187 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_int;
																		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 193 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_inicio;
																		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 199 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_fim;
																		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 205 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_and;
																		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 212 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_de;
																		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 218 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_ate;
																		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 224 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_reals;
																		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 230 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_return;
																		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 236 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_real;
																		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 242 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_not;
																		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_passo;
																		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 254 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_print;
																		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 260 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_read;
																		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 266 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_minimo;
																		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 272 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_central;
																		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 278 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_maximo;
																		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 285 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_repeat;
																		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 292 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_switch;
																		}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 300 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_case;
																		}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 307 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_default;
																		}																		
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 314 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("PALAVRARESERVADA %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_switch_end;
																		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 323 "scanner.l"
{
																			return token_aspas;
																		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 326 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_atrib;
																		}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 332 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_maior;
																		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 338 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_maior_igual;
																		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 344 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_menor;
																		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 350 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_menor_igual;
																		}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 356 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_igual;
																		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 362 "scanner.l"
{				
																			#ifdef DEBUG 
																				printf("SIMBOLOESPECIAL %s na linha %d\n", yytext, nlinhas); 
																			#endif
																			return token_diferente;
																		}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 368 "scanner.l"
{return token_increment;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 369 "scanner.l"
{return token_decrement;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 370 "scanner.l"
{return token_mod;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 371 "scanner.l"
{return token_mais;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 372 "scanner.l"
{return token_menos;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 373 "scanner.l"
{return token_div;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 374 "scanner.l"
{return token_mult;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 375 "scanner.l"
{return token_pot;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 377 "scanner.l"
{return token_colchete_abre ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 378 "scanner.l"
{return token_colchete_fecha;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 379 "scanner.l"
{return token_abreParen;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 380 "scanner.l"
{return token_fechaParen;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 381 "scanner.l"
{return token_pt;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 382 "scanner.l"
{return token_virg;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 383 "scanner.l"
{return token_pt_virg;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 384 "scanner.l"
{return token_dois_pt;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 385 "scanner.l"
{return token_hashtag;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 386 "scanner.l"
{return token_chaves_abre;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 387 "scanner.l"
{return token_chaves_fecha;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 388 "scanner.l"
{return token_apost;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 389 "scanner.l"
{return token_cbarra;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 391 "scanner.l"
{strcpy (vlr_int, yytext); return token_vlr_inteiro;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 392 "scanner.l"
{return token_vlr_real;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 393 "scanner.l"
{return token_vlr_char;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 394 "scanner.l"
{return token_true;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 395 "scanner.l"
{return token_false;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 396 "scanner.l"
{strcpy(ident,yytext); return token_ident;}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 397 "scanner.l"
{return token_vlr_string;}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 398 "scanner.l"
{/*printf("COMENTARIO IGNORADO\n")	;*/ contaLinhas(yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 399 "scanner.l"
/*{printf("COMENTARIO DE LINHA IGNORADO\n")	;}*/
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 401 "scanner.l"
;
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 402 "scanner.l"
{nlinhas++;/* printf("nlinhas = %d [ENTER]\n", nlinhas);*/} 
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 403 "scanner.l"
{printf("Erro na linha %d, %s: SIMBOLO DESCONHECIDO \n", nlinhas, yytext);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 405 "scanner.l"
ECHO;
	YY_BREAK
#line 1907 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 538 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 538 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 537);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 405 "scanner.l"


int yywrap()
{
	printf("%d Linhas\n", nlinhas);
	return(1);
}



